[project]
name = "review-dashboard-project"
version = "0.1.0"
description = "Dashboard for Shopee/Lazada reviews"
requires-python = ">=3.12,<3.13"
dependencies = [
    "streamlit",
    "sqlalchemy",
    "pandas",
    "requests",
]