# ================= Google Service Account =================
[SERVICE_AC]
type = "service_account"
project_id = "webfujikathailand"
private_key_id = "0aafa26660496fb4089d314a54e6a7e7ed699b17"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDXBzYP7oyR1wsg
...
-----END PRIVATE KEY-----"""
client_email = "svgscfujith@webfujikathailand.iam.gserviceaccount.com"
client_id = "114611274948393385571"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/svgscfujith%40webfujikathailand.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[users.admin]
email = "admin@e.com"
password = "fujika2023"
role = "admin"

[users.aftersales]
email = "aftersales@e.com"
password = "fujikaservice"
role = "service"

[users.marketing]
email = "marketing@e.com"
password = "mamaidersometing"
role = "marketing"

[users.shopee_test]
email = "shopee@test.com"
password = "test1289"
role = "shopee_test"
