[users.admin]
email = "admin@e.com"
password = "fujika2023"
role = "admin"

[users.aftersales]
email = "aftersales@e.com"
password = "fujikaservice"
role = "service"

[users.marketing]
email = "marketing@e.com"
password = "mamaidersometing"
role = "marketing"

[users.shopee_test]
email = "shopee@test.com"
password = "test1289"
role = "shopee_test"
