# ================= Google Service Account =================
[SERVICE_AC]
type = "service_account"
project_id = "webfujikathailand"
private_key_id = "0aafa26660496fb4089d314a54e6a7e7ed699b17"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDXBzYP7oyR1wsg
pUloPlNFxbPTy4ZBe3krRQohzRM9im2B72upF7OzHEueQUuiN45CScX0CHOIMaC2
s/5wuc3ZDIsjLGDIadUsigsrkFitOKhXfspTUsKyEH8Z5br6TCTdzik6n12ddNd0
DKUhyXpto4XjZLphbKnkITdv/g8NM7XCGVLpURYolg4GsotI/jJSmHmg548cOxEn
/asphXxZRXqsIji21Hgao4x7H3fB6NJ+GkzLSkTWT8WroX104Saao50ppFB2Ps38
U4NrZ7/IsUf5NV4MCm8+h4CzJjoapaTejViero7Ogs6YU+WdNa9kGZix3lWBqNLk
VUTcpMjTAgMBAAECggEAFW4TDcBtAwXnBoBikgCQJQaAlw2UGkeXel/9lAPPtJTs
uAPn+2iw0Jtzz9hbFNYrl+CpWVpURVEI3tyOcaaa5NRSs5UzKhYeGDvDxDo1FEJu
yJWKzYYUgFGTkT2rhlF7ZR2sTzrdxhkEdfziojzltjKTX+fEiXwebG2BDGjKEDsV
yGY3sGJEs6wXobdkefv3dvun6UgH15BqRR/pzKbyWqeDzJWY4WchIKXMcvF2HVlm
mmeuXhmnm/m+65WN5HcIRFKLp3eMPyLqf32uQiW5l25ahoUa6k0+hzdRob2ZZTBc
IFr7ozAgFYq0NDLGnYZq+kuR3ttUrjMYmYHA+dMfdQKBgQDze2PGM/3msFqsNajL
wVWV5fIisznhiG2GRbzoBUNY3Su61mVKbimilGZEm3C9ONRxYYPQtDF0q7XwzKaO
5/5FPvvivZ9heUiKqsplHtgh96XRGgCDSg8bboZ8CcX/IbqnZUn9uu2XaVIrB6vs
iikdcgrCzDQHRZDXzswgupASBQKBgQDiFVLprJENBRYJib31LDM5mNZHXt/6xH4A
4LeafoOX7Z0NpuyNv1QsaHlSvaU9xENRG7bjVmpAYCqF0nBcKFDP8RKX6Rnk8nOQ
JMmzjyJBBF9Ssz6Y0Pyvr7asAD3o/EJStrJLu/X8ceC2G6QopRtTqCePlbNCl71U
1fy/GxSu9wKBgFz4AGDt+UTckcKvuoQSjltuMcaOKMu1DBz5A+iUGeMUkF4G/yYs
ajlp8KLBt4qI6JViZrKKG1gxOId5nR9z9eL66bLqNLFDXi+UhzOVU3Gk3eu5wfhf
juUqjq9ODAwfFOZWBqqbdZ0a2gUUKNFo78oOgY1f633bUjMVA1x74AcBAoGBAKMW
ltUSMyCdRqRixLETzXADHLAndJNFI1Amysub7/ms4tpyS7qFBodyZfKV85l29siP
oYKlV8hQltwqTfts6b7XPH5xHMjXTR3yK75nxmH4cXsK6mD6gQ2LR88T7ZUgRAe+
2yde07fjviIgFm9riybx6nfdmY60P1PveX+yXV1JAoGBAOd/s24rD+2FG4auqvLl
Su5X9Fga9LWfsi89oVx1C2CoW4pwdhvuUvn8HixXyBhjoZBSFtPoy79PB9xV3oZg
hP/IcAwGt9vgoD6gUkegfoqkVk4rO2IYDGkABN8k1oBSymGu0NhB8E4K9SWLpQgX
LJJCGfSSOi44TKA/hqWzbwYG
-----END PRIVATE KEY-----
"""
client_email = "svgscfujith@webfujikathailand.iam.gserviceaccount.com"
client_id = "114611274948393385571"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/svgscfujith@webfujikathailand.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


[users.admin]
email = "admin@e.com"
password = "fujika2023"
role = "admin"

[users.aftersales]
email = "aftersales@e.com"
password = "fujikaservice"
role = "service"

[users.marketing]
email = "marketing@e.com"
password = "mamaidersometing"
role = "marketing"

[users.shopee_test]
email = "shopee@test.com"
password = "test1289"
role = "shopee_test"

[SERVICE_ACCOUNT_JSON]
type = "service_account"
project_id = "shopeetoken-469704"
private_key_id = "4889a0509922ba7a2b78e33a558227b9577bc85a"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC79fpqv8lDMk/y
sGn6O89E6ImCtEM7mL0lUWfHd0bj/qCZLpueXFJ2IhvcRpvUcPxdfDN2A1h89AhJ
7KzALSVOheawlRvBeQfQEVDPhpH9G+nDjOCu3of1ETHbG1KfbK4DwxpHd6Nzmkiw
4YfFGBjZARPWoi+XBzk0Fbi8z8kfOLNsLe43IjVggq//QSpD7QNFqLvSc1L/+0+P
pKKSGXjQBozPRV5xVeeabNaqEmDdDy3uR5k30yiWG3QJBsB89AOZ7sju0IbgGV9Y
/yS/XegRK+QdhSmlPoGSZfo/IeoxbSpOgRHerkoWHZbZGnXpJwGM2fopyHZyxQs8
c3hxkocBAgMBAAECgf9tpGRvNhuGbH2LvrITRiWiDK4qOvz9HBvkU5g2GAiXoUYN
angHPdOHFbPVdVrGkcyku86eXf/q48ScsB1qp5XGOFWuq/baOmpUSnAunlE1VGhd
qdARhxMdNuqI5WdM7W3qGTqQdeQ4NceGvAh28EI4/mfpdrJMEeqhzLShbz6NoYVt
dcb/HgsF8JgJFUHFxDtbHXCOz4CzqWqFu+od2XFcX41XADN/TYjiubZdPzdvt9HY
iXz2lr72lEFTOBxSVfFWk5uvs/VaMUrrUrCMf++bRUA8hrCt5WdQ40lPbf2p7oxy
Ee8RltGuy8DiSB04nKpQBz5mU0ez3LEgQ4KLLQECgYEA5zHymfvdSvfYLY+tJF1G
Iof7DQzxg+by/CN/Ejv5yywt53ffzJrlL54rFHChSuI05TxIlI8Qee+FzBjK5XLo
hska++/oKHOx6xS9UD58uDohQAMHuGJhwwicjrUTZeRbwqWtgWW4uqYHSM/ygLBs
EgsfhsR9UoebMItyJl0KFz8CgYEA0CCMsSm8Rr1ETwy0F9zluj7MUZ44j+8JRD/j
rAViuCMEy4wpyPvcqfKrBO2C8oXSapX0uzrqCbRQI4f990FHmxbLUkJf1cHcEBMz
pLkgWxYdvhdxkXsAB+OSrFevtv98eCfEDoU0nB1RjpWq0YCg2DUcWql1+ZXG5G0U
zUSAEb8CgYEA4JEJnzygZPN9DjRi79GSEHSZDMInzgGEwBkSkvmi1xDgvdcYkbtb
JvexzLbiVMSIsKnvri2QyYA5LFhgrKMC7flltpX/oVtP1JJemRU5PBFqvqyy0Qzu
/OzedVe5sd0wrE8Vy3ytBM/Ef5tNaGb1cklPpC4ztPh3a53nkRAKfy0CgYEAiZtr
ylsg29iZyHZKwJhR38FTkAc/uJLAGrrvSjZJXhvxOK+UlQlJjagfwONUuAsY41YA
eKZsRTxN3CA3H3qu4HDCv8GY4ZkKaip388pfBTprMdsIQLsFezHRMVfMmv7zCfKo
4zzZWvrbiJ2WUmxsbGc5NwxiL0IDPdaNcWaAErsCgYBdzLDUR5Rzj6jJxcbD/Vxb
P1ww8fwJ5HMDPbqN+CLjEz9oXj9xlsumJBlR5FMspNgid0F7qI0nofLQ0TWodgQr
fZbtTxnCZvp4SJ808Hf/T9h9HQU8RZZqZbq840tsRuXKKlSyjehRDT7r0eKotamb
VwCGorkQrRgOAAIyIq9Kkg==
-----END PRIVATE KEY-----
"""
client_email = "shopeefortoken@shopeetoken-469704.iam.gserviceaccount.com"
client_id = "109580806711230857224"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/shopeefortoken@shopeetoken-469704.iam.gserviceaccount.com"
universe_domain = "googleapis.com"